module.exports = {
  GET_NAMES: "GET_NAMES",
  SAVE_NAMES: "SAVE_NAMES",
  DUPE_NAME: "DUPE_NAME",
  DUPE_SCORE: "DUPE_SCORE",
  OVER100: "OVER100",
  CLEAR_ERROR: "CLEAR_ERROR",
  OVER_STARTERS: "OVER_STARTERS",
  OVER_SUBS: "OVER_SUBS",
  ROSTER_LIMIT: "ROSTER_LIMIT",
  EDIT_NAME: "EDIT_NAME"
};
